-- Migration 013: Persistent notifications table
-- Stores notifications generated by Moon (WhatsApp leads, messages)
-- and other system events. Survives frontend refresh.
-- NotificationDropdown polls this via GET /api/notifications.

CREATE TABLE notifications (
  id         TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  title      TEXT NOT NULL,
  message    TEXT NOT NULL,
  type       TEXT NOT NULL DEFAULT 'info',
  lead_id    TEXT REFERENCES leads(id) ON DELETE SET NULL,
  read       BOOLEAN NOT NULL DEFAULT false,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for polling queries: unread-first, newest-first
CREATE INDEX idx_notifications_read    ON notifications(read);
CREATE INDEX idx_notifications_created ON notifications(created_at DESC);
CREATE INDEX idx_notifications_lead_id ON notifications(lead_id);
